server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
#        native:
#          search-locations: file://${user.home}/project/kyh/msa-basic/config
        git:
          uri: https://github.com/yh0921k/spring-cloud-msa-basic
          search-paths: config
          default-label: master
#          username:
#          password:
#          uri: file:///Users/kyh/project/temp/local-config
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
