server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yh0921k/spring-cloud-msa-basic
          search-paths: config
#          uri: file:///Users/kyh/project/temp/local-config