server:
  port: 8888

spring:
  application:
    name: config-service
#  profiles:
#    active: native
  cloud:
    config:
      server:
#        native:
#          search-locations: file://${user.home}/project/temp/config-repo
        git:
          uri: https://github.com/yh0921k/spring-cloud-msa-basic
          search-paths: config
#          uri: file:///Users/kyh/project/temp/local-config