version: "3"

services:
  db:
    image: mariadb:10
    ports:
      - 3306:3306
    volumes:
      - ~/project/database/db/conf.d:/etc/mysql/conf.d
      - ~/project/database/db/data:/var/lib/mysql
      - ~/project/database/db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - backend
    restart: always

networks:
  backend:
